[versions]
kotlin = "2.4.10"
junit = "5.11.4"
spotless = "8.10.3"
detekt = "2.0.0-alpha.6"

[libraries]
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
spotless-gradle-plugin = { module = "com.diffplug.spotless:com.diffplug.spotless.gradle.plugin", version.ref = "spotless" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
detekt-gradle-plugin = { module = "dev.detekt:dev.detekt.gradle.plugin", version.ref = "detekt" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
detekt = { id = "dev.detekt", version.ref = "detekt" }

patch4j-kotlin = { id = "patch4j.kotlin-convention" }
patch4j-root = { id = "patch4j.root" }